//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressStorekeepers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressStorekeepers()
        {
            this.Publication = new HashSet<Publication>();
        }
    
        public int AdressStoreroomID { get; set; }
        public string AdStCity { get; set; }
        public string AdStStreet { get; set; }
        public string AdStHouse { get; set; }
        public string AdStCorps { get; set; }
        public Nullable<int> AdStEntrance { get; set; }
        public string AdStSpecialMarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publication { get; set; }
    }
}
