//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public string LibLogin { get; set; }
        public string LibSurname { get; set; }
        public string LibName { get; set; }
        public string LibPatronymic { get; set; }
        public string LibPassword { get; set; }
        public Nullable<bool> LibAdmin { get; set; }
    }
}
