//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int PublicationID { get; set; }
        public string PublicationName { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> TypePublicationID { get; set; }
        public Nullable<int> PublisherID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<int> Circulation { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> AdressStorekeepID { get; set; }
        public Nullable<System.DateTime> DatePrinting { get; set; }
        public Nullable<System.DateTime> DateAdmission { get; set; }
    
        public virtual AddressStorekeepers AddressStorekeepers { get; set; }
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual TypePublication TypePublication { get; set; }
    }
}
